[package]
authors = ["Hongxu <hongxuchen1989@gmail.com>"]
name = "rs_snippets"
version = "0.1.0"

[dependencies]
bson = "0.8"
bytecount = "0.1.6"
clang = "0.16.0"
clap = "2"
cpython = "0.1"
curl = "0.4.6"
fs_extra = "1.0.0"
futures = "0.1.14"
hyper = "0.11"
itertools = "0.6.0"
libc = "0.2"
log = "0.3"
log4rs = "0.7.0"
memmap = "0.5.2"
mio = "0.6"
mongodb = "0.3.0"
ncurses = "5.85.0"
nix = "0.8.0"
nom = "^3.1"
notify = "4.0.0"
num = "0.1"
num_cpus = "1.6.2"
pbr = "1.0.0"
quickcheck = "0.3"
rand = "0.3"
rayon = "0.8.1"
redis = "0.5.3"
regex = "0.2.2"
rulinalg = "0.4.2"
scoped_threadpool = "0.1.7"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
shmem = "0.2.0"
simd = "0.2.0"
sysinfo = "0.3.8"
threadpool = "1.3.2"
time = "0.1.37"
tokio-core = "0.1.8"
toml = "0.4"
unicorn = "0.7.0"
url = "1.5.0"

[features]
avx-accel = ["bytecount/avx-accel"]
simd-accel = ["bytecount/simd-accel"]

[lib]
doc = false
doctest = false
name = "mylib"
path = "src/lib/mods.rs"
test = false

[profile]

[profile.bench]
codegen-units = 1
debug = false
debug-assertions = false
lto = false
opt-level = 3
panic = "unwind"
rpath = false

[profile.dev]
codegen-units = 1
debug = true
debug-assertions = true
lto = false
opt-level = 0
panic = "unwind"
rpath = false

[profile.doc]
codegen-units = 1
debug = true
debug-assertions = true
lto = false
opt-level = 0
panic = "unwind"
rpath = false

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = false
opt-level = 3
panic = "unwind"
rpath = false

[profile.test]
codegen-units = 1
debug = true
debug-assertions = true
lto = false
opt-level = 0
panic = "unwind"
rpath = false
